# Generated by Django 3.0.5 on 2020-06-08 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resolutions', '0015_delete_customfixcomments'),
        ('users', '0002_auto_20200328_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFixComments',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=3000)),
                ('date_comment_made', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('fix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolutions.CustomFixes')),
            ],
        ),
    ]
