# Generated by Django 3.0.5 on 2020-06-08 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0015_delete_customfixcomments'),
        ('comments', '0003_manualfixcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualfixcomment',
            name='manual_fix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolutions.ManualFix'),
        ),
    ]
