# Generated by Django 3.0.5 on 2020-05-13 21:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resolutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechTipPics',
            fields=[
                ('tt_photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_caption', models.CharField(max_length=60)),
                ('photo', models.ImageField(upload_to='tech_tip_pics')),
                ('tech_tip_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolutions.TechTipFix')),
            ],
        ),
    ]
