# Generated by Django 3.0.4 on 2020-03-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_image',
            field=models.ImageField(default='article.jpg', upload_to='article-pics'),
        ),
    ]
