# Generated by Django 3.0.4 on 2020-03-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_image',
            field=models.ImageField(default='article.jpg', upload_to='article_pics'),
        ),
    ]
