# Generated by Django 3.0.4 on 2020-03-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200323_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_image',
            field=models.ImageField(default='default.jpg', upload_to='article_pics'),
        ),
    ]
