# Generated by Django 3.0.4 on 2020-03-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200327_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_image',
            field=models.ImageField(default='article_pics\\default.jpg', upload_to='article_pics'),
        ),
    ]
