# Generated by Django 3.0.5 on 2020-05-13 21:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('error_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_name', models.CharField(help_text='A simple description of the issue. Should be simple to search for this.EX: H4-02 or black line', max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('error_title', models.CharField(help_text='A short description of the error', max_length=200)),
                ('error_description', models.TextField(help_text='A more detailed description of the issue: Do not use for resolutions', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TechTipFix',
            fields=[
                ('tech_tip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tech_tip_number', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tech_tip_title', models.CharField(max_length=300)),
                ('tech_tip_content', models.TextField(max_length=10000)),
                ('model_id', models.ManyToManyField(to='library.ProductModel')),
                ('repairs_error', models.ManyToManyField(to='resolutions.Error')),
            ],
        ),
        migrations.CreateModel(
            name='ManualFix',
            fields=[
                ('manual_fix_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('steps_to_fix_error', models.TextField(max_length=3000)),
                ('model_id', models.ManyToManyField(to='library.ProductModel')),
                ('repairs_error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolutions.Error')),
            ],
        ),
    ]
