# Generated by Django 3.0.5 on 2020-05-16 19:18

from django.db import migrations, models
import django.utils.timezone
import library.datum


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0002_customfixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfixes',
            name='created_on_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customfixes',
            name='modified_on_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customfixes',
            name='id_number',
            field=models.CharField(default=library.datum.alphanumeric_generator, max_length=8, unique=True),
        ),
    ]
