# Generated by Django 3.0.5 on 2020-05-16 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0003_auto_20200516_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='techtipfix',
            name='tech_tip_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
