# Generated by Django 3.0.5 on 2020-05-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0004_techtipfix_tech_tip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techtipfix',
            name='tech_tip_date',
            field=models.DateField(),
        ),
    ]
