# Generated by Django 3.0.5 on 2020-06-04 18:06

from django.db import migrations, models
import library.datum


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0005_auto_20200516_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualfix',
            name='slug',
            field=models.SlugField(default=library.datum.alphanumeric_generator, editable=False, max_length=8, unique=True),
        ),
    ]
