# Generated by Django 3.0.5 on 2020-06-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0006_manualfix_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualfix',
            name='slug',
            field=models.SlugField(default='F0F0EDCE', editable=False, max_length=8, unique=True),
        ),
    ]
