# Generated by Django 3.0.5 on 2020-06-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0008_auto_20200604_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualfix',
            name='slug',
        ),
    ]
