# Generated by Django 3.0.5 on 2020-06-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0009_remove_manualfix_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualfix',
            name='slug',
            field=models.SlugField(blank=True, max_length=8),
        ),
    ]
