# Generated by Django 3.0.5 on 2020-06-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0010_manualfix_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualfix',
            name='id',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
