# Generated by Django 3.0.5 on 2020-06-04 18:24

from django.db import migrations, models
import library.datum


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0011_manualfix_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualfix',
            name='id',
            field=models.CharField(default=library.datum.alphanumeric_generator, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='manualfix',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
