# Generated by Django 3.0.5 on 2020-06-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0012_auto_20200604_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'ordering': ['error_name']},
        ),
        migrations.AddField(
            model_name='customfixes',
            name='symptoms',
            field=models.CharField(default='sample symptom', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customfixes',
            name='steps_to_fix_error',
            field=models.TextField(),
        ),
    ]
