# Generated by Django 3.0.5 on 2020-06-08 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0028_auto_20200601_1149'),
        ('users', '0002_auto_20200328_1143'),
        ('resolutions', '0013_auto_20200606_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfixes',
            name='model_id',
            field=models.ManyToManyField(help_text='select one or multiple models', to='library.ProductModel'),
        ),
        migrations.AlterField(
            model_name='customfixes',
            name='repairs_error',
            field=models.ManyToManyField(help_text='Select one or multiple errors', to='resolutions.Error'),
        ),
        migrations.AlterField(
            model_name='customfixes',
            name='symptoms',
            field=models.CharField(help_text='Describe any symptoms that accompany error', max_length=400),
        ),
        migrations.AlterField(
            model_name='techtipfix',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='CustomFixComments',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=3000)),
                ('date_comment_made', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('fix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolutions.CustomFixes')),
            ],
        ),
    ]
