# Generated by Django 3.0.5 on 2020-06-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0014_auto_20200608_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFixComments',
        ),
    ]
