# Generated by Django 3.0.5 on 2020-07-09 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resolutions', '0016_manualfix_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='created_on_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
