# Generated by Django 3.0.5 on 2020-06-22 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageHit',
            fields=[
                ('hit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('visitor', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.URLField()),
                ('num_page_views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
