# Generated by Django 3.0.5 on 2020-06-22 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehit',
            name='page',
            field=models.ForeignKey(default=44, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tracking.PageView'),
            preserve_default=False,
        ),
    ]
