# Generated by Django 3.0.5 on 2020-06-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_pagehit_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='page_category',
            field=models.CharField(default='tech-tip', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageview',
            name='page_identifier',
            field=models.CharField(default='tech', max_length=25),
            preserve_default=False,
        ),
    ]
