# Generated by Django 3.0.5 on 2020-06-28 16:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20200624_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageDailyViews',
            fields=[
                ('daily_view_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_page_views', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tracking.PageView')),
            ],
        ),
    ]
