# Generated by Django 3.0.5 on 2020-07-10 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20200702_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagehit',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['pagehit__date']},
        ),
        migrations.AlterField(
            model_name='pagehit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
