# Generated by Django 3.0.5 on 2020-07-11 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20200710_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagedailyviews',
            options={'ordering': ['date']},
        ),
        migrations.CreateModel(
            name='PageRanking',
            fields=[
                ('page_ranking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('ranking', models.PositiveSmallIntegerField(unique_for_date=models.DateTimeField())),
                ('page', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tracking.PageView')),
            ],
        ),
    ]
