# Generated by Django 3.0.5 on 2020-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20200711_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageranking',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='pageview',
            name='page_category',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='page_identifier',
            field=models.CharField(max_length=250),
        ),
    ]
